name: handygram
description: A light Wear OS Telegram client - HandyGram
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.10.0'

dependencies:
  flutter:
    sdk: flutter

  wear:
    git:
      url: https://github.com/ju851zel/flutter_wear_plugin
      ref: upgrade-versions
  # original package is discounted :(
  flutter_ffmpeg:
    git:
      url: https://github.com/SongTube/flutter-ffmpeg
      ref: master
  flutter_riverpod: ^2.3.0
  carousel_slider: ^4.2.1
  rotary_scrollbar: ^0.1.1
  path_provider: ^2.0.11
  device_info_plus: ^9.0.0
  pretty_qr_code: ^2.0.3
  video_player: ^2.5.1
  scrollable_positioned_list: ^0.3.5
  mutex: ^3.0.1
  visibility_detector: ^0.4.0+2
  hive: ^2.2.3
  async: ^2.10.0
  ffi: ^2.0.1
  audioplayers: ^4.0.1
  scrollview_observer: ^1.10.1
  positioned_scroll_observer: ^2.2.0
  google_fonts: ^4.0.4
  flutter_emoji: ^2.4.0
  video_thumbnail: ^0.5.3
  lottie: ^2.3.2
  workmanager: ^0.5.1
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
