name: handygram
description: Telegram client for WearOS
publish_to: 'none'
version: '1.0.0-lynx'

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  async: ^2.11.0
  audioplayers: ^6.0.0
  connectivity_plus: ^6.0.2
  curved_text: ^0.2.0
  device_info_plus: ^10.1.0
  dio: ^5.4.2+1
  fc_native_video_thumbnail: ^0.12.0
  ffi: ^2.1.3
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  handy_tdlib: any
  hive: ^2.2.3
  intl: any
  json: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.2.0
  lottie: ^3.1.2
  meta: any
  mutex: ^3.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pretty_qr_code: ^3.3.0
  scroll_to_index: ^3.0.1
  scrollview_observer: ^1.21.0
  vector_graphics: ^1.1.11+1
  vibration: ^2.0.0
  video_player: ^2.8.7
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  material_color_utilities: any
  vector_graphics_compiler: ^1.1.11+1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/vectors/compiled/
    - assets/images/
    - .git/HEAD
    - .git/refs/heads/

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Variable.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        # - asset: assets/fonts/roboto/Roboto-Thin.ttf
        #   style: normal
        #   weight: 100
        # - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
        #   style: italic
        #   weight: 100
        # - asset: assets/fonts/roboto/Roboto-Light.ttf
        #   style: normal
        #   weight: 300
        # - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        #   style: italic
        #   weight: 300
        # - asset: assets/fonts/roboto/Roboto-Black.ttf
        #   style: normal
        #   weight: 900
        # - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
        #   style: italic
        #   weight: 900
flutter_intl:
  enabled: true
  class_name: AppLocalizations
